Uikit buttons
qase-tms/shelterpaws pull request #43
Opened 2024-01-12 11:47 UTC by Tabarzin

Added default btns and hover state

2024-01-12 16:04 UTC, Christik requested changes
Рустам, очень здорово получилось!)

2024-01-12 16:04 UTC, Christik commented on frontend/src/templates/pages/ui/index.njk
> +  <path d="M8 1.375C8 2.4565 6.59 3.8005 5.8875 4.364C5.77757 4.45213 5.64089 4.50015 5.5 4.50015C5.35911 4.50015 5.22243 4.45213 5.1125 4.364C4.41 3.8 3 2.4565 3 1.375C2.98423 1.02711 3.10689 0.6871
[+] Сейчас можно оставить так, как есть. Но вообще у нас планируется сделать иконки, как отдельный компонент. Когда они будут готовы, можно будет вставить вместо свг.

2024-01-12 16:04 UTC, Christik commented on package.json
> +    "gulp": "^4.0.2"
[?] Здесь такой же вопросик, что и с хаски) Это намерено сделано, или случайно?)

2024-01-13 10:54 UTC, Tabarzin commented on frontend/src/templates/pages/ui/index.njk
> +  <path d="M8 1.375C8 2.4565 6.59 3.8005 5.8875 4.364C5.77757 4.45213 5.64089 4.50015 5.5 4.50015C5.35911 4.50015 5.22243 4.45213 5.1125 4.364C4.41 3.8 3 2.4565 3 1.375C2.98423 1.02711 3.10689 0.6871
Можешь пояснить, плз, что значит иконки как отдельный компонент в данном случае? Картинкой или как?

2024-01-13 10:56 UTC, Tabarzin commented on package.json
> +    "gulp": "^4.0.2"
Это я пытался решить проблему с хаски и переустанавливал разные штуки, и так оно сюда попало. Галп удалил, но такие штуки остались:
"gulp-autoprefixer": "^9.0.0",
    "gulp-nunjucks-render": "^2.2.3",
    "gulp-sass": "^5.1.0",

2024-01-14 05:06 UTC, Christik commented on frontend/src/templates/pages/ui/index.njk
> +  <path d="M8 1.375C8 2.4565 6.59 3.8005 5.8875 4.364C5.77757 4.45213 5.64089 4.50015 5.5 4.50015C5.35911 4.50015 5.22243 4.45213 5.1125 4.364C4.41 3.8 3 2.4565 3 1.375C2.98423 1.02711 3.10689 0.6871
По поводу реализации надо еще подумать. Но я имела ввиду что-то типа

```
<button>
    <i class="icon icon--donate"></i>
    Donate
</button>
```

Но возможно, иконки придется оставлять svg из-за поддержки браузеров. Но надо будет подумать, как сократить код)

2024-01-14 05:08 UTC, merged