Uikit controls
qase-tms/shelterpaws pull request #44
Opened 2024-01-12 14:18 UTC by Tabarzin

Added controls

2024-01-12 16:30 UTC, Christik requested changes
🔥

2024-01-12 16:30 UTC, Christik commented on frontend/src/scss/ui/_description.scss
> +.description {
[!] Давай, пожалуйста, переименуем этот компонент в что-то вроде `.param-list`. Description - очень общее название, оно еще часто будет у нас встречаться в верстке))

2024-01-12 16:30 UTC, Christik commented on frontend/src/scss/ui/_description.scss
> +  color: rgba(41, 42, 53, 0.5);
[+] В scss есть крутая штука - более удобный `rgba`. Можно переписать так:

`color: rgba($primary-txt-color, 50%);`

Плюс такой записи в том, что мы используем общую переменную. И когда появятся другие темы и изменятся цвета, то внутри этого компонента уже не нужно будет ничего менять.

2024-01-12 16:30 UTC, Christik commented on frontend/src/scss/ui/_description.scss
> +  font-family: $primary-font;
[+] Вроде как здесь необязательно указывать шрифт, потому что он наследуется от родителей.

2024-01-12 16:30 UTC, Christik commented on frontend/src/scss/ui/_description.scss
> +  line-height: 140%;
[+] `line-height` лучше выражать как 1.4. Это некритично, но бывают кейсы, когда проценты и другие относительные единицы в `line-height` странно себя ведут))

Можно почитать на mdn: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#prefer_unitless_numbers_for_line-height_values

2024-01-12 16:30 UTC, Christik commented on frontend/src/scss/ui/_description.scss
> +  list-style: none;
[!] Мы не сбрасывали стили, а использовали нормализацию, поэтому помимо list-style нужно еще обнулить маргины и паддинги) Если посмотреть в инспекторе кода, то они там есть)

2024-01-12 16:30 UTC, Christik commented on frontend/src/scss/ui/_filter.scss
> +  font-style: normal;
[+] Это свойство можно опустить, по умолчанию и так будет normal

2024-01-12 16:30 UTC, Christik commented on frontend/src/scss/ui/_filter.scss
> +  line-height: 150%;
[+] Аналогично, здесь можно изменить на `1.5`

2024-01-12 16:30 UTC, Christik commented on frontend/src/scss/ui/_filter.scss
> +  list-style: none;
[!] Аналогично, еще нужно сбросить маргины и паддинги))

2024-01-12 16:30 UTC, Christik commented on frontend/src/scss/ui/_description.scss
> +    }
[+] Здесь можно сделать немного иначе:

Избавиться от флексов.
Убрать отрицательные мартигы.
:after позиционировать абсолютно, а у item задать правый паддинг.

Плюс все-таки лучше сделать кружочек через стили, а не свг))

Если что-то будет непонятно, пиши, разберемся)

2024-01-12 16:30 UTC, Christik commented on frontend/src/scss/ui/_filter.scss
> +    }
[+] Здесь можно сделать такую же логику, как и у списка параметров

2024-01-12 16:30 UTC, Christik commented on frontend/src/scss/ui/_filter.scss
> +    border-bottom: 2px transparent solid;
[+] Сама только недавно начала этим пользоваться, но сейчас подчеркивания можно хорошо стилизовать через text-derocation))

2024-01-12 16:30 UTC, Christik commented on frontend/src/scss/ui/_filter.scss
> +    &:hover {
[+] Ховер, как и в ПРе с кнопками можно доработать)

2024-01-12 16:30 UTC, Christik commented on frontend/src/scss/ui/_filter.scss
> +      border-bottom-color: rgba(41, 42, 53, 0.15);
[+] Здесь тоже можно использовать переменную с цветом

2024-01-13 11:34 UTC, Tabarzin commented on frontend/src/scss/ui/_description.scss
> +    }
Переделал кружок на стилях, убрал вообще свг и псевдоэлемент.

2024-01-13 11:51 UTC, Tabarzin commented on frontend/src/scss/ui/_filter.scss
> +    border-bottom: 2px transparent solid;
Попробовал переделать с text-decoration. Не знаю, то ли ты имела в виду, но вроде работает.

2024-01-14 05:28 UTC, Christik requested changes
Перепроверь, пожалуйста, опечатки в html)) Если их подправить, то визуально увидишь, что еще нужно подправить в стилях))

2024-01-14 05:28 UTC, Christik commented on frontend/package.json
> -    "gulp": "^4.0.2",
[!!!] Здесь не надо было удалять галп)) В папке frontent он нужен, а в корне проекта не нужен

2024-01-14 05:28 UTC, Christik commented on frontend/src/templates/pages/ui/index.njk
> +      <a class="filter__link href="#">
[!!!] Перепроверь, пожалуйста, весь html на ошибки. Тут есть опечатки, не проставлены кавычки после имени класса. К сожалению, линтер для html еще не настроен и ошибки не ловятся.

2024-01-14 05:28 UTC, Christik commented on frontend/src/templates/pages/ui/index.njk
> +      <div class="param-list__circle"></div>
[!] Кружочек лучше сделать псевдоэлементом. Тогда html код станет немного чище))

2024-01-16 17:53 UTC, merged