Add header
qase-tms/shelterpaws pull request #45
Opened 2024-01-12 18:28 UTC by hellagirrl

2024-01-16 18:01 UTC, serikovlearning commented on frontend/src/templates/general/footer.njk
> +        <div class="section-name">
Данный элемент выглядит как заголовок.
В _mixins.scss был миксин, кажется, для h2, в котором уже был задан подходящий размер шрифта.
Думаю, лучше стоит использовать именно его, чтобы заголовки в секциях не отличались чем-то кроме цвета

2024-01-16 18:02 UTC, serikovlearning commented on frontend/src/templates/general/footer.njk
> +        <div class="page-footer__sideinfo">
В REAMDE.md указано, что используем БЭМ и приведён пример как `.block--modifier`
Кажется, что стоит привести к одному виду

2024-01-16 18:03 UTC, serikovlearning commented on frontend/src/templates/general/header.njk
> +<script>
Думаю, что стоит вынести скрипт в отдельный файл в папочку `static`

2024-01-16 18:04 UTC, serikovlearning commented on frontend/src/templates/general/header.njk
> +    burger.classList.toggle('burger--opened', force);
А расскажи пожалуйста что такое force? Впервые вижу второй параметр у метода `toggle`

2024-01-16 18:05 UTC, serikovlearning commented on frontend/src/templates/general/header.njk
> +    addEventListener('hashchange', event => {
А для чего нам изменять мобильное меню на событие hashchange?
Что/кто является слушателем события в данном случае?

2024-01-16 18:07 UTC, serikovlearning commented on frontend/src/templates/general/header.njk
> +let burger;
Мне кажется, что вместо вынесения переменной для `NodeElement`, было бы лучше получать её в `init() ` и передавать в `toggleMobileMenu` вторым аргументом. 

Как думаешь?

2024-01-16 18:09 UTC, serikovlearning commented on frontend/src/scss/layout/_header.scss
> +    --height: 3px;
А мы можем здесь использовать переменные в стиле scss?

2024-01-16 18:11 UTC, serikovlearning commented on frontend/src/scss/layout/_header.scss
> +  @media (width <= 1024px)  {
Кристина заводила в _mixins.scss миксины для медиа-запросов.
Посмотри пожалуйста, мне кажется, что стоит использовать их

2024-01-17 05:36 UTC, Andrenord282 commented on frontend/src/templates/general/header.njk
> +    burger.classList.toggle('burger--opened', force);
> А расскажи пожалуйста что такое force? Впервые вижу второй параметр у метода `toggle`

тоже удивился, а оказывается вот как это работает:

> Метод toggle() принимает только один класс для переключения. Опционально вторым аргументом можно передать boolean-значение: метод будет работать как add(), если передать true, и как remove(), если передать false.

2024-01-17 07:31 UTC, Christik requested changes
Большую работу проделала, молодец! ❤️

2024-01-17 07:31 UTC, Christik commented on frontend/src/scss/layout/_layout.scss
> +.body--menu-opened {
[?] Подскажи, плиз, а у нас есть где-то класс `.body`? Если нет, то сам по себе модификатор не может существовать. Тогда лучше переименовать на `.body-menu-opened`.

2024-01-17 07:31 UTC, Christik commented on frontend/src/templates/general/footer.njk
> +                    <p>+3 123 456 789</p>
[!] Номера телефонов лучше сделать ссылками, чтобы сразу можно было набрать.))

2024-01-17 07:31 UTC, Christik commented on frontend/src/templates/general/footer.njk
> +                    <p>info@site.com</p>
[!] Почту тоже можно сделать ссылкой.

2024-01-17 07:31 UTC, Christik commented on frontend/src/templates/general/header.njk
> +<script>
Согласна, но это я предложила Кате пока писать скрипт в <script>. В сборке пока не обрабатываются js файлы. Можно будет отрефакторить это, когда сборка обновится)

2024-01-17 07:59 UTC, hellagirrl commented on frontend/src/templates/general/footer.njk
> +        <div class="section-name">
да, спасибо! не уследила за ПР-ом с миксинами, сейчас поправлю

2024-01-17 08:09 UTC, hellagirrl commented on frontend/src/templates/general/header.njk
> +    addEventListener('hashchange', event => {
это нужно чтобы менюшка с бургером закрывалась при клике на элемент менюшки (пользователь кликает на, например,  'Main' и вместо того чтобы кликать на кнопку закрытия бургера, бургер закрывается сам)

2024-01-17 08:14 UTC, hellagirrl commented on frontend/src/templates/general/header.njk
> +let burger;
```
const toggleMobileMenu = (force, burger) => {
    const menu = document.querySelector('.page-menu');

    burger.classList.toggle('burger--opened', force);
    menu.classList.toggle('page-menu--opened', force);
    document.body.classList.toggle('body--menu-opened', force);
};

const init = () => {
    const burger = document.querySelector('.burger');

    burger.addEventListener('click', () => toggleMobileMenu(true, burger));

    addEventListener('hashchange', event => {
        toggleMobileMenu(false, burger);
    });
};

document.addEventListener('DOMContentLoaded', init);
```

про такой способ говоришь? хм, мне кажется первый более читаемым, но я тебе доверюсь в выборе кусочка который оставляем

2024-01-17 08:15 UTC, hellagirrl commented on frontend/src/scss/layout/_header.scss
> +    --height: 3px;
да, вынесу!

2024-01-17 08:20 UTC, hellagirrl commented on frontend/src/templates/general/header.njk
> +    addEventListener('hashchange', event => {
```
const init = () => {
    burger = document.querySelector('.burger');
    const menu_item = document.querySelectorAll('.burger > span');

    menu_item.forEach(item => item.addEventListener('click', () => toggleMobileMenu()))
    burger.addEventListener('click', () => toggleMobileMenu());
};

```

hashchange можно таким кусочком заменить, что думаешь?

2024-01-17 08:21 UTC, serikovlearning commented on frontend/src/templates/general/header.njk
> +let burger;
Да, всё так

2024-01-18 12:22 UTC, hellagirrl commented on frontend/src/scss/layout/_footer.scss
> +  .container {
вот, тоже хотела спросить про это! после фиксов в итоге от этого блока удалось избавиться, и как раз по БЭМ'у получилось :)

2024-01-18 12:23 UTC, hellagirrl commented on frontend/src/scss/layout/_footer.scss
> +  height: 100%;
тоже поправила, раньше нужна была потому что кусочек снизу оставался, после фиксов с container'ом необходимость в этом стиле ушла :)

2024-01-18 13:31 UTC, hellagirrl commented on frontend/src/scss/layout/_footer.scss
> +      line-height: 39.2px;
не нашла :( но оставлю тогда как 1.25, спасибо!

2024-01-18 13:38 UTC, hellagirrl commented on frontend/src/scss/layout/_header.scss
> +  .burger__dash:nth-child(2) {
точно, поправила, спасибо!

2024-01-18 14:33 UTC, hellagirrl commented on frontend/src/scss/layout/_footer.scss
> +  }
тогда если что после Лешиного ПР'а вернусь к этому)

2024-01-20 05:31 UTC, Christik requested changes
Катя, получается вообще красота! 😃

2024-01-20 05:31 UTC, Christik commented on frontend/src/scss/layout/_header.scss
> +  .logo {
[+] Давай, пожалуйста, следовать именованию БЭМ)) Это есть в требованиях. Такое наследование типа `.page-header .logo` увеличивает специфичность и верстка становится менее гибкой, ее труднее масштабировать.

Здесь можно логотип сделать элементом шапки: `.page-header__logo`.

А вот ниже `.page-menu` имеет свою вложенную структуру и ее можно вынести из `.page-header`, чтобы `.page-menu` был блоком (в терминах БЭМ). И тогда при необходимости мы сможем переиспользовать менюшку в подвале, если друг понадобится. 

Этот коммент относится ко всем местам, где увеличена специфичность))

2024-01-20 05:31 UTC, Christik commented on frontend/src/scss/layout/_header.scss
> +      transition: 0.5s;
👍 Красота)

2024-01-20 05:31 UTC, Christik commented on frontend/src/scss/layout/_header.scss
> +  }
[+] Можно немного упросить код и нижнюю границу сделать одной строчкой с помощью `border-bottom` у `.page-header__in`. Если что, прозрачность цвета в scss можно задавать с помощью `rgba`. Например: `border-bottom: 1px solid rgba($white, 10%)`

2024-01-20 05:31 UTC, Christik commented on frontend/src/scss/layout/_header.scss
> +  }
[+] Здесь и в других местах адаптивные медиа запросы типа `@include for-desktop` можно помещать внутрь элемента для лучше читабельности))

2024-01-20 05:31 UTC, Christik commented on frontend/src/scss/layout/_header.scss
> +      transition: transform 0.5s;
Анимация огонь 🔥

2024-01-20 05:31 UTC, Christik commented on frontend/src/scss/layout/_header.scss
> +    .page-menu {
[!!!] Перепроверь, пожалуйста, менюшку на мобильных, там поломалось. Если что, у нас поддержка адаптива от 320px

![Screenshot 2024-01-20 081016](https://github.com/qase-tms/shelterpaws/assets/2283411/488fe5fd-2a3b-4b01-9dc5-dc89bbc8a5e8)

2024-01-20 05:31 UTC, Christik commented on frontend/src/templates/general/footer.njk
> +{% set footer_databag = { international_number: "+7 987 654 32 10", european_number: "+3 123 456 789", location: "Georgia, Poti", email: "info@site.com", button: { text: "Donate", link: "/donate" } }
Вообще красота, сразу данные вынесены!) Единственное, я бы только отформатировала код, а то читается тяжело. Пока у нас нет притиера, поэтому пока вручную надо.

2024-01-20 05:31 UTC, Christik commented on frontend/src/templates/general/footer.njk
> +            alt="footer picture"
[+] В идеале альтернативный текст должен отражать, что на картинке. Здесь можно было бы прокидывать название шелтера типа: `alt="shelter The territory of goodness"`

2024-01-20 05:31 UTC, Christik commented on frontend/src/templates/general/footer.njk
> +                  <a href="{{ 'tel:' ~ footer_databag.international_number }}">{{ footer_databag.international_number }}</a>
[!] Телефон внутри атрибута `href `не должен иметь пробелов и знаков. Например: `href="tel:6031112298"`

2024-01-20 05:31 UTC, Christik commented on frontend/src/templates/general/footer.njk
> +              <button class="button" type="button">{{ footer_databag.button.text }}</button>
[!] Я не уверена, что здесь будет меняться текст кнопки. Лучше уточнить у Витали, какая тут логика.

2024-01-20 05:31 UTC, Christik commented on frontend/src/scss/layout/_footer.scss
> +  }
[?] Расскажи, плиз, а почему картинку скрываешь при адаптиве?

2024-01-20 05:31 UTC, Christik commented on frontend/src/scss/_mixins.scss
> +@mixin for-tablet-up {
[!] В данном случае здесь подходит название `for-tablet-down.` Типа планшеты и все, что ниже. А up это планшеты и все, что выше.

2024-01-20 05:33 UTC, Christik commented on frontend/src/scss/_vars.scss
> +$burger-translate-y: calc($burger-dash-margin / 3 + $burger-dash-height);
[+] Я бы не стала выносить эти переменные в общий файл. Их можно сделать локальными внутри бургера, потому что нигде больше они не нужны))

2024-01-25 09:24 UTC, hellagirrl commented on frontend/src/scss/layout/_header.scss
> +  background-color: $inverse-primary-bg-color;
точно, убрала! тогда пока фон белый, а как появится промо секция, должно все заработать :)

2024-01-25 10:00 UTC, hellagirrl commented on frontend/src/scss/layout/_header.scss
> +  }
супер, добавила! сейчас, правда, не видно этой линии при открытом бургере, но как я понимаю это не так критично

2024-01-25 10:28 UTC, hellagirrl commented on frontend/src/scss/layout/_footer.scss
> +  }
мне кажется, как будто так получше выглядит + у нас нет дизайна для мобильных устройств, поэтому не знаю как еще можно

а ты как думаешь?

2024-01-27 04:56 UTC, Christik commented on frontend/src/scss/layout/_footer.scss
> +  }
Я бы оставила картинку на мобиле, но пусть это будет на твое усмотрение)

2024-01-27 05:04 UTC, Christik requested changes
Вообще отлично! 👍  

Только перепроверь, пожалуйста, мобильное меню. В адаптиве отступы нужно подправить и размер текста.

<img width="510" alt="Screenshot 2024-01-27 at 07 56 54" src="https://github.com/qase-tms/shelterpaws/assets/2283411/32c2afa9-5a17-444e-ab53-f7b1436cec26">

Мы уже на финишной прямой! Последние правки и будем мержить)

2024-01-27 05:04 UTC, Christik commented on frontend/src/scss/layout/_footer.scss
> +    }
[!] Все супер, только в этом месте опять увеличивается специфичность. Давай, плиз, вынесем `.contact-row` в отдельный компонент. Можно просто стили вынести в отдельный файл в ui. А то сейчас `.contact-row` нельзя переиспользовать в других местах.

2024-01-27 09:25 UTC, hellagirrl commented on frontend/src/scss/layout/_footer.scss
> +    }
о, хорошо, супер!

2024-01-27 11:16 UTC, hellagirrl commented on frontend/src/scss/layout/_footer.scss
> +  }
оставила! так и правда поприятнее выглядит)

2024-01-28 04:35 UTC, merged