#issue_40 add about section
qase-tms/shelterpaws pull request #56
Opened 2024-01-16 14:12 UTC by Salexg34

2024-01-16 17:41 UTC, serikovlearning commented on .vscode/settings.json
> +{
Это не нужно в проекте, нужно удалить
Кажется, забыли добавить в .gitignore

2024-01-16 17:41 UTC, serikovlearning commented on frontend/package.json
> +  "dependencies": {
Для чего обновление данных зависимостей?

2024-01-16 17:42 UTC, serikovlearning commented on frontend/yarn.lock
> +dom-walk@^0.1.0:
У нас не должно быть обновлений зависимости в PR c вёрсткой секций

2024-01-16 17:57 UTC, serikovlearning commented on frontend/src/scss/pages/index/sections/_about.scss
> +    @include for-tablet {
Изменения размеров шрифтов в медиа, я бы сохранил в родительском миксине, котороый идёт к h1.

2024-01-16 17:57 UTC, serikovlearning commented on frontend/src/scss/pages/index/sections/_about.scss
> +    @include for-tablet {
Аналогично как и выше, можно утащить в параграф, чтобы во всех параграфах был один размер шрифта

2024-01-17 07:14 UTC, Christik commented on .vscode/settings.json
> +{
Да, на меня стоит ишью с обновление гитигнора, пока руки не дошли. Можно, кстати, кому-нибудь дать эту мелкую задачку)

2024-01-17 07:30 UTC, Christik requested changes
Очень здорово получается, молодец!)

2024-01-17 07:30 UTC, Christik commented on frontend/src/scss/pages/index/sections/_about.scss
> +    margin: 40px auto 0;
Мне кажется, тут лучше пиксели оставить)) 
em в маргинах хорошо использовать для текстовых элементов. В этом случае при изменении размера текста (например, при адаптиве) внешние отступы изменятся пропорционально.

Так получилось, что сейчас в верстке в основном используются пиксели. У нас простой дизайн без масштабирования, и с px чуть проще разобраться джунам.))

2024-01-17 07:30 UTC, Christik commented on frontend/src/scss/pages/index/sections/_about.scss
> +    @include for-tablet {
Леш, подскажи, пожалуйста, а на чем ты основывался при изменении размеров в адаптиве? У нас нет макетов под адаптив)

2024-01-17 07:30 UTC, Christik commented on frontend/src/scss/pages/index/sections/_about.scss
> +.about {
[?] Подскажи, пожалуйста, а зачем этот класс, если есть .about-seciton?))

2024-01-17 07:30 UTC, Christik commented on frontend/src/templates/pages/index/sections/about_section.njk
> +    <div class="about--content">
[!!!] Смотри, получается нарушение именования БЭМ. Здесь у нас есть `about-section`. А потом висящие в воздухе модификаторы `about--**`.  Мне кажется, ты перепутал, модификаторы с элементами))

Здесь надо будет пересмотреть именование всех элементов:
- блок: `.block`
- модификатор: `.block--modifier`
- элемент: `.block__element`

Плюс разобраться с .about, об этом есть коммент выше.
Просто у нас все секции имеют именование `.name-section`. И было бы здорово поддерживать консистентность))

2024-01-17 07:30 UTC, Christik commented on frontend/src/scss/pages/index/sections/_about.scss
> +  }
[!] Пропустил требование из описания ишью)) Надо вынести заголовок секции в ui компонент, т.к. эти блоки можно переиспользовать во всех секциях)

2024-01-17 07:30 UTC, Christik commented on frontend/src/scss/pages/index/sections/_about.scss
> +  &--video {
[+] И еще в ишью было требование вынести адаптивное видео в общий компонент) Но если нет желания, пока можно оставить так. А когда видео появятся в других местах, то уже вынести в общий компонент.

2024-01-17 12:34 UTC, Salexg34 commented on frontend/src/scss/pages/index/sections/_about.scss
> +    @include for-tablet {
Основывался исключительно на своих внутренних убеждениях))) в ишью была задача дапатива под 320, а в макете ничего об этом, ну я и подумал что можно поимпровизировать

2024-01-22 13:28 UTC, Christik requested changes
Леша, получается здорово! Осталось еще чуть-чуть доработать и можно будет мержить))

2024-01-22 13:28 UTC, Christik commented on frontend/src/scss/pages/index/sections/_about.scss
> +    @include for-tablet {
Согласна. У нас есть миксин `@include loud`, который соответствует такому тексту. Давай его использовать))

2024-01-22 13:28 UTC, Christik commented on frontend/src/scss/pages/index/sections/_about.scss
> +    width: 67%;
[!] Давай здесь лучше зададим максимальную ширину в px. Отступы по бокам нужны только на десктопе. На мобиле у нас и так мало места, а сейчас мы его сокращаем еще больше.

2024-01-22 13:28 UTC, Christik commented on frontend/src/scss/pages/index/sections/_about.scss
> +      width: 65%;
[!] Давай здесь тоже уберем ширину в процентах и зададим максимальную ширину в px. И тогда у родителя можно будет убрать width: fit-content

2024-01-22 13:28 UTC, Christik commented on frontend/src/scss/pages/index/sections/_about.scss
> +    }
[!] Сейчас работает не совсем так, как задумано) Блок с видео должен сохранять пропорции ширины и высоты, и при этом ресайзиться при изменении ширины экрана.

Плюс здесь тоже давай будем уходить от ширины в процентах. Лучше максимальная ширина в пикселях. На мобильных у нас весь контент должен занимать всю доступную ширину.

Реализацию можно подсмотреть здесь: https://dev.to/deammer/embed-responsive-youtube-videos-in-2021-5dkh

2024-01-22 13:28 UTC, Christik commented on frontend/src/templates/pages/index/sections/about_section.njk
> +      </h4>
[+] Давай лучше здесь сделаем просто параграф `<p>`, потому что сейчас нарушается последовательность заголовков. Заголовок h4 может идти только если перед ним стоит h3.

2024-01-22 13:28 UTC, Christik commented on frontend/src/templates/pages/index/sections/about_section.njk
> +    </p>
[!] Этот текст будет вставляться из админки. То есть владелец шелтера сам будет вводить этот текст в редакторе текста в админке. А там может быть несколько абзацев, или списки (нумерованные и ненумерованные). Поэтому давай сделаем такую структуру:

```
<div class="about-section__text">
    // здесь может быть любое наполнение
    <p>text</p>
    <p>text</p>
</div>
```

2024-01-23 11:54 UTC, serikovlearning commented on frontend/src/templates/pages/index/sections/about_section.njk
> +    </p>
Здесь не очень согласен.
Кажется, что мы не планируем делать админку под лендинги.

2024-01-23 11:54 UTC, serikovlearning commented on frontend/src/templates/pages/index/sections/about_section.njk
> +    </p>
Предлагаю оставить это для интеграции именно с бэком

2024-01-24 13:03 UTC, Christik commented on frontend/src/templates/pages/index/sections/about_section.njk
> +    </p>
Не совсем поняла) Владелец шелтора же должен заполнять информацию о своем приюте, верно? Они будут загружать фотки животных с информацией, описание приюта, видео. Или я что-то не так понимаю?)

2024-01-24 13:46 UTC, Christik requested changes
Движемся в правильном направлении, так держать! ))

2024-01-24 13:46 UTC, Christik commented on frontend/src/scss/_mixins.scss
> +  }
[!] Давай, плиз, здесь уберем адаптив. Не стоит слишком мельчить. Если текст выглядит слишком огромным, то логично его уменьшить в адаптиве. А здесь 18px смотрятся норм на мобилах. Главное, чтобы читать было удобно))

2024-01-24 13:46 UTC, Christik commented on frontend/src/scss/_mixins.scss
> +  }
[!] Здесь тоже давай, пожалуйста, уберем адаптив, чтобы не мельчить)

2024-01-24 13:46 UTC, Christik commented on frontend/src/scss/pages/ui/_index.scss
> +section {
[!!!] Леш, про общие компоненты не совсем правильно понял))

Посмотри, пожалуйста, на пример того, как Рустам делает компоненты кнопок. Этот ПР еще не смержен, но логика там заложена правильная:
https://github.com/qase-tms/shelterpaws/pull/58/files

Давай разберем на примере шапки секции.
Назовем этот компонент `section-header`. Структура будет такая:
```
.section-header {
  &__sup-title {}
  &__title {}
}
```
Стили компонента выносим в отдельный файл с таким же названием, как и сам компонент: /scss/ui/_section-header.scss

Все стили, которые лежат в папке /pages/ относятся к соответствующим страницам. Здесь не стоит прописывать какие-то глобальные классы.

С компонентом видео то же самое)) Если будут вопросы, пиши)

2024-01-24 13:46 UTC, Christik commented on frontend/src/scss/pages/ui/_index.scss
> +    margin: 40px auto 0;
[!] Когда будешь переносить эти стили, надо будет убрать маргины. В БЭМ блок не должен иметь внешние отступы, т.к. это характеристика того, как блок взаимодействует с соседями. А блок - это независимая единица вне контекста. 

Маргины нужно указывать элементу. Конкретно в этом кейсе маргины будут внутри секции у элемента .about-section__video.

2024-01-24 13:46 UTC, Christik commented on frontend/src/templates/ui/section_header.njk
> +{% endmacro %}
Макрос огонь!) Только классы надо переименовать по БЭМ, как я выше писала. И сама шапка будет тегом `<header>`, а не `<div>`

2024-01-27 05:13 UTC, Christik requested changes
Осталось по мелочи подправить) Ты молодец!

2024-01-27 05:13 UTC, Christik commented on frontend/src/scss/_mixins.scss
> -  @include paragraph;
[?] Расскажи, плиз, почему это удалил?

2024-01-27 05:13 UTC, Christik commented on frontend/src/scss/ui/_section-header.scss
> +    &__sub-title {
[+] Это не подзаголовок, а НАДзаголовок)) Поэтому логичнее было бы обозвать `sup`

2024-01-28 04:51 UTC, Christik requested changes
Последние фиксы) Перепроверь, плиз, перед пушем, чтобы все отображалось норм.

2024-01-28 04:51 UTC, Christik commented on frontend/src/scss/ui/_section-header.scss
> +    &__sub-title {
[!!!] Сейчас стили не применяются, надо привести все именования к одному виду. Здесь должно быть `sup`

2024-01-28 04:51 UTC, Christik commented on frontend/src/scss/ui/_section-header.scss
> +    &__main-heading {
[!] Давай переименуем покороче: `title`

2024-01-28 04:51 UTC, Christik commented on frontend/src/templates/pages/index/sections/about_section.njk
> +    {{ section_header(sup_title="Who Are We", heading="About the shelter", className="about-section__header") }}
[!] `title` вместо `heading`, чтобы все имена консистентны были

2024-01-28 04:51 UTC, Christik commented on frontend/src/templates/ui/section_header.njk
> +    <h2 class="section-header__main-heading">
[!] `title`

2024-01-28 04:51 UTC, Christik commented on frontend/src/templates/ui/section_header.njk
> +{% macro section_header(sub_title="", heading="", className="") %}
[!] И тут `title` вместо `heading`

2024-01-30 13:06 UTC, merged