Feat/create-promo-section/#39
qase-tms/shelterpaws pull request #59
Opened 2024-01-17 14:51 UTC by Andrenord282

Сверстал секцию promo-section.
В других ПР видел вопросы на счет адаптива были, поэтому пока не делал.

2024-01-18 15:05 UTC, Christik requested changes
Очень здорово, спасибо за ПР ❤️ 

Только нужно долить потерянные картинки и сделать адаптив.
Для адаптива размер заголовка можешь менять прямо внутри миксина `heading1`

2024-01-18 15:05 UTC, Christik commented on frontend/src/templates/pages/index/sections/promo_section.njk
> +    </div>
Структура html прямо конфетка! Очень нравится, все по БЭМ ❤️

2024-01-18 15:05 UTC, Christik commented on frontend/src/scss/pages/index/sections/_promo.scss
> +    }
[+] А еще можно так, чтобы легче читался код:

```
    &__btn-list {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 0 30px;
        max-width: 470px;

        &-item {
            @include sidePadding(56px);
        }
    }
```

2024-01-21 04:36 UTC, Christik requested changes
Получается очень круто, ты молодец! 🔥 
Последний рывок и потом будем мержить))

2024-01-21 04:36 UTC, Christik commented on frontend/src/scss/pages/index/sections/_promo.scss
> +        max-width: 1440px;
[?] Подскажи, плиз, а зачем тут переопределил максимальную ширину? В макете она 1200 вместе с отступами. По умолчанию .container такую макс ширину и имеет.

2024-01-21 04:36 UTC, Christik commented on frontend/src/scss/pages/index/sections/_promo.scss
> +        }
[!] Давай не будем обнулять отступ? В любом случае содержимое секции никогда не должно вплотную располагаться к границе.

2024-01-21 04:36 UTC, Christik commented on frontend/src/scss/pages/index/sections/_promo.scss
> +            width: 100%;
[+] Эту ширину можно без адаптивного миксина применить.

2024-01-21 04:36 UTC, Christik commented on frontend/src/scss/pages/index/sections/_promo.scss
> +            }
[!] Очень здорово, что паддинги для адаптива поменял! А давай эти стили перенесем в компонент кнопки, чтобы они ко всем кнопочкам применялись)) Это полезно

2024-01-21 04:36 UTC, Christik commented on frontend/src/scss/pages/index/sections/_promo.scss
> +    background-image: url('#{$img-path}/_promo/promo-bg-desktop.jpg');
[!!!] Путь до картинки неверный.

2024-01-21 04:36 UTC, Christik commented on frontend/src/scss/pages/index/sections/_promo.scss
> +        }
[!] Давай, пожалуйста, немного доработаем мобильный адаптив, а то сейчас на мобилах маленькая собачка ютится в правом нижнем углу))

Предлагаю что-то типа такого варианта:

![Screenshot 2024-01-21 072646](https://github.com/qase-tms/shelterpaws/assets/2283411/0f2d2a93-4bb8-4314-ab1c-392405762bbc)

Для мобильных:
- убрать высоту 100vh;
- убрать у собаки абсолютное позиционирование;
- выстроить контент и собаку в колонку;
- убрать у секции нижний паддинг, чтобы собака касалась нижней границы;
- задать контейнеру с собакой ширину 100%, но ограничить максимальной шириной в 400px, чтобы она не была слишком огромной на широких мобилах;
- задать контейнеру с собакой боковые паддинги в 40px, чтобы смотрелось более гармонично;
- убрать максимальную ширину у заголовка, текста и кнопок.

Если будут вопроси, пиши))

2024-01-21 10:33 UTC, Andrenord282 commented on frontend/src/scss/pages/index/sections/_promo.scss
> +        max-width: 1440px;
> [?] Подскажи, плиз, а зачем тут переопределил максимальную ширину? В макете она 1200 вместе с отступами. По умолчанию .container такую макс ширину и имеет.

у меня такой ход мыслей к решению был:
1. у нас собачка + блок с текстом шире нашего контейнера по умолчанию, 1288 пикселей.
2. собачку я решил сделать абсолютно и позиционировал в первый раз относительно блока .promo-section.
3. но потом протестировал и заметил, что .promo-section занимает всю ширину экрана, и если смотреть на большом разрешении 2к и 4к выходит, что собачка очень далеко от текста.
4. я подумал, что нужно ограничить ширину .promo-section до 1440 пикселей либо сделать .promo-section__container с ограничением 1440 пикселей и относительно этого контейнера ставить собачку

сейчас я немного по-другому переделал

2024-01-21 10:47 UTC, Andrenord282 commented on frontend/src/scss/pages/index/sections/_promo.scss
> +            }
> [!] Очень здорово, что паддинги для адаптива поменял! А давай эти стили перенесем в компонент кнопки, чтобы они ко всем кнопочкам применялись)) Это полезно

`@include sidePadding(38px);` предлагаю по умолчанию в кнопках изменить паддинг еще

2024-01-24 13:58 UTC, Christik requested changes
Один маленький фикс и будем мержить))

2024-01-24 13:58 UTC, Christik commented on frontend/src/scss/pages/index/sections/_promo.scss
> +    background-image: url('#{$img-path}/promo-section/promo-bg-desktop.jpg');
[!] Ура, картинки появились!)) Только подскажи, плиз, где ты ужимал картинку фона? Сейчас прям очень плохого качества. Я советую на tinypng.com ужимать, там и ужимает хорошо, и в качестве не теряет. Пересохрани, плиз)

2024-01-27 04:01 UTC, merged