Feat/create statistics section/qase-tms#41
qase-tms/shelterpaws pull request #63
Opened 2024-01-28 14:16 UTC by Andrenord282

Сверстал секцию со статистикой и адаптировал ее под мобильные устройства.

Сделал анимацию появления лап и анимацию счетчиков, которые показывают статистику.
Лапы появляются постепенно как будто прошлась собака, потом медленно исчезают, если такая идея понравится, то я предлагаю на главном экране анимировать тоже так лапы (сейчас они просто на фоне нарисованы и все).

2024-01-28 14:19 UTC, Andrenord282 commented on frontend/src/scss/pages/index/sections/_statistic.scss
> +        }
У нас в миксинах есть шрифт heading2, я видел в другом ПР ставили уже, но я посмотрел, мне показались там значение маленькие для мобилок, сюда поставил побольше, может поставим как у меня тут?

2024-01-28 14:20 UTC, Andrenord282 commented on frontend/src/scss/pages/index/sections/_statistic.scss
> +        }
такого шрифта у нас нет в миксинах, предлагаю вынести, как лучше его записать?

2024-01-30 13:21 UTC, Christik commented on frontend/src/scss/pages/index/sections/_statistic.scss
> +            flex: 0 1 100%;
[+] Если меняется только одно значение, а первые два остаются прежними, то лучше переопределить только `flex-basis`

2024-01-30 13:21 UTC, Christik commented on frontend/src/scss/pages/index/sections/_statistic.scss
> +        }
Согласна) Давай сделаем везде, как у тебя 👍

2024-01-30 13:24 UTC, Christik commented on frontend/src/scss/pages/index/sections/_statistic.scss
> +.statistic-section__descr {
[+] Может, обзовем этот элемент `.statistic-section__cta`? Имеется ввиду call to action. И сокращения нет, и по смыслу подходит.

2024-01-30 13:27 UTC, Christik commented on frontend/src/scss/pages/index/sections/_statistic.scss
> +        }
Если этот шрифт не повторяется, то давай пока не будем его выносить в общие миксины. Сейчас в миксины вынесена типографика, которую дизайнер вынес в ui, то есть по задумке дизайнера они будут переиспользоваться.

2024-01-30 13:30 UTC, Christik commented on frontend/src/scss/pages/index/sections/_statistic.scss
> +    transition: all 0.2s linear;
[+] Не хватает `pointer-events: none`, чтобы на этих декорациях не срабатывало выделение мышью

2024-01-30 13:36 UTC, Christik commented on frontend/src/templates/pages/index/sections/statistic_section.njk
> +  <script>
[?] Ты весь этот скрипт сам написал?))

2024-01-30 13:41 UTC, Christik commented on frontend/src/static/img/general/dog-paw-left.svg
[+] Еще когда смотрела на верстку промо секции, хотела предложить лапки отдельными картинками заверстать, чтобы их можно было в этой секции переиспользовать))

В данном кейсе это некритично, т.к. страничка не тяжелая. Но если есть желание заморочиться, то можно немного оптимизировать. То есть в промо секции фон сделать нативным градиентом, а лапки вот этими картинками. Но это необязательно)

2024-01-30 13:48 UTC, Christik commented
[!] Еще один важный коммент вдогонку) В чатике решили, что будем делать разные темы для сайта и менять только стили. Поэтому давай, пожалуйста, сразу на это заложимся и переверстаем лапки. Сделаем их не тегами `<img />`, а поставим на фон дивов через `background: url()`

Это более правильно и с точки зрения семантики. Обычно все, что касается дизайна и декораций, должно быть реализовано с помощью стилей. А если изображение несет смысловую нагрузку, то это <img />. Но это в идеальном мире)) Конечно, не всегда так получается делать.

Если будут вопросики, пиши)

2024-01-30 13:56 UTC, Christik commented on frontend/src/templates/pages/index/sections/statistic_section.njk
> +  linkHref: '#'
[!!!] Здесь у тебя ссылочка, а внизу <button>)) Скорее всего, кнопка в будущем будет модалку вызывать, поэтому это будет button

2024-02-01 10:11 UTC, Andrenord282 commented on frontend/src/static/img/general/dog-paw-left.svg
Идея хорошая, тоже об этом думал, можно будет отдельным таскам подправить этот момент, плюс анимацию сделать на классах
Возьмусь если желающих не будет)

2024-02-01 10:38 UTC, Andrenord282 commented
> [!] Еще один важный коммент вдогонку) В чатике решили, что будем делать разные темы для сайта и менять только стили. Поэтому давай, пожалуйста, сразу на это заложимся и переверстаем лапки. Сделаем их не тегами `<img />`, а поставим на фон дивов через `background: url()`
> 
Правки эти тоже внес)

2024-02-04 05:11 UTC, Christik requested changes
Супер! Давай подправим микро коммент и будем мержить)

2024-02-04 05:11 UTC, Christik commented on frontend/src/scss/_mixins.scss
> +@mixin for-desktop-up {
[+] Давай здесь назовем миксин `for-wide-desktop` или `for-large-desktop`, потому что брейкпоинт уже новый. А `-up` и `-down` добавляем, когда от какого-то промежуточного брейкпоинта и выше (или ниже)

2024-02-08 03:37 UTC, Christik requested changes
Отлично, спасибо!) Давай конфликты порешаем, а то не дает смержить)

2024-02-08 05:21 UTC, merged