Feat: create animals section and create ui card of element/#62
qase-tms/shelterpaws pull request #67
Opened 2024-02-08 08:18 UTC by Andrenord282

2024-02-09 11:19 UTC, Christik requested changes
Выглядит потрясающе! ❤️

2024-02-09 11:19 UTC, Christik commented on frontend/src/scss/ui/_card.scss
> +.card {
[+] Давай, плиз, переименуем файлы и класс в `animal-card`. А то мало ли какие еще карточки в будущем добавятся)

2024-02-09 11:19 UTC, Christik commented on frontend/src/scss/ui/_card.scss
> +    cursor: pointer;
[?] А зачем `cursor: pointer`, если сейчас карточка некликабельная?)

2024-02-09 11:19 UTC, Christik commented on frontend/src/scss/ui/_card.scss
> +        & img {
[!] Давай, пожалуйста, будем следовать принципам БЭМ и не увеличивать специфичность) 

Можно, пример, так:

```
.card {
  &__preview {
    &-img {}
  
```}
}

2024-02-09 11:19 UTC, Christik commented on frontend/src/static/img/animals-section/card-01.jpg
[!] Смотри, у нас в /static/ есть 2 папки для картинок: /img/ и /upload/

В /img/ кладем все изображения, которые относятся к дизайну (лапки там сейчас лежат правильно)
А в /upload/ кладем изображения, которые относятся к контенту и должны лежать в базе данных: фото животных, фото шелтера

2024-02-09 11:19 UTC, Christik commented on frontend/src/templates/pages/index/sections/animals_section.njk
> +  <div class="container animals-sectio__container">
[!] Опечатка: animals-**sectio**__container

2024-02-09 11:19 UTC, Christik commented on frontend/src/templates/pages/index/sections/animals_section.njk
> +          </a>
[?] А можем сразу сделать простой фильтр на js? Например, добавить к карточке data-атрибут, который обозначал бы тип животного. Что-то типа `<li class="card-list__item card" data-type="dog">` А при клике на фильтр Dogs или Cats показывать только тех, на кого кликнули, и скрывать остальных.

Если что, это по желанию) Мы можем сделать под это дело отдельную задачку, если надо)

2024-02-09 11:19 UTC, Christik commented on frontend/src/templates/pages/index/sections/animals_section.njk
> +              <img src="{{card.imgSrc}}"/>
[+] Можно еще добавить изображению alt и выводить там имя

2024-02-09 11:19 UTC, Christik commented on frontend/src/templates/pages/index/sections/animals_section.njk
> +</div>
[!] Перепроверь здесь, плиз. Мне кажется, здесь напутало с открывающими и закрывающими тегами

2024-02-09 11:19 UTC, Christik commented on frontend/src/templates/ui/card.njk
> +<li class="card">
[!] У нас есть этот шаблон, но в нем хардкорно прописаны все значения и он не используется нигде)) Давай, отрефакторим это, чтобы данный шаблон можно было использоваться внутри секции?

Карточка животного может переиспользоваться и в других местах на сайте)

2024-02-11 03:23 UTC, Andrenord282 commented on frontend/src/scss/ui/_card.scss
> +        & img {
![image](https://github.com/qase-tms/shelterpaws/assets/79256226/f02b6e29-ee88-46f8-ae06-2f1f1827e954)
![image](https://github.com/qase-tms/shelterpaws/assets/79256226/6f7fa565-cf20-4a76-b2f4-580ba379827f)
подскажи как тут решить? если писать как на первом скрине, то выходит неправильная сборка css
в итоге я написал по-другому немного

2024-02-11 03:24 UTC, Andrenord282 commented on frontend/src/scss/ui/_card.scss
> +    cursor: pointer;
тут мой недочет, как думаешь нужно сделать? что бы по самой карточке можно было кликнуть и пройти на страничку самой карточки, или что бы по имени можно было кликнуть и пройти по ссылке?

2024-02-11 03:43 UTC, Andrenord282 commented on frontend/src/scss/ui/_card.scss
> +    cursor: pointer;
я пока сделал на саму карточку ссылку

2024-02-11 13:40 UTC, Andrenord282 commented on frontend/src/scss/pages/index/sections/_animals.scss
> +    }
я переделал, но не уверен, что вы так хотели сделать

2024-02-11 13:59 UTC, Andrenord282 commented on frontend/src/scss/ui/_card.scss
> +    cursor: pointer;
добавил еще в макрос, что бы карточку можно было использовать с ссылкой и без

2024-02-11 15:04 UTC, Andrenord282 commented on frontend/src/templates/pages/index/sections/animals_section.njk
> +          </a>
сделал пока простенький самый)

2024-02-12 16:56 UTC, Christik requested changes
Получается вообще огонь!) Мне очень нравится)

2024-02-12 16:56 UTC, Christik commented on frontend/src/scss/pages/index/sections/_animals.scss
> +        }
[+] Выглядит отлично) Но с точки зрения реализации, лучше обновить компонент `section_header` и добавить ему проп `align`, который будет задавать выключку текста: по центру или по левому краю. Проп необязательный, по умолчанию center. В секции контактов заголовок тоже выравнивается по левому краю. Только там еще не внедрен компонент section_header. Без дополнительного пропса align придется дублировать кусок кода))

Это по желанию) Я могу под это дело создать отдельный ишью. Только отпишись мне, плиз, чтобы я не забыла это сделать)

2024-02-12 16:56 UTC, Christik commented on frontend/src/scss/ui/_animal-card-list.scss
> +.animal-card-list {
Отличная идея - вынести сетку карточек) Она может переиспользоваться. Лайк)

2024-02-12 16:56 UTC, Christik commented on frontend/src/scss/ui/_animal-card.scss
> +    transition: all 0.2s linear;
[!] Здесь transition вроде лишний, на самой карточке анимации нет

2024-02-12 16:56 UTC, Christik commented on frontend/src/scss/ui/_animal-card.scss
> +            transition: transform 0.2s linear;
[!] Здесь transition дублируется. На 26 строке то же самое. Поэтому можно удалить)

2024-02-12 16:56 UTC, Christik commented on frontend/src/scss/ui/_animal-card.scss
> +        & .animal-card__preview-img {
[+] Смотри, какая фича есть у scss: `$this: &`

В чем плюсы такого варианта:
- Поведение при наведении описывается внутри `&-img`, к которому и относится. То есть код легче читается.
- Нет дублировать имен классов. Если вдруг захотим переименовать `.animal-card` во что-то другое, то нужно будет внести правку всего в одно место в коде

Твой вариант тоже рабочий, если что))

<img width="736" alt="Screenshot 2024-02-12 at 19 44 03" src="https://github.com/qase-tms/shelterpaws/assets/2283411/dab4a068-add8-439f-9df2-4cf52312bcec">

2024-02-12 16:56 UTC, Christik commented on frontend/src/templates/pages/index/sections/animals_section.njk
> +              }, 100)
[+] Этот кусок кода дублируется 3 раза, значит, можно вынести его в функцию)

2024-02-13 03:09 UTC, Andrenord282 commented on frontend/src/scss/ui/_animal-card.scss
> +    transition: all 0.2s linear;
`  transition: opacity 0.2s linear;`
предлагаю так сделать, когда идет фильтрация то в начале у карточки opacity меняем потом display, если transition убрать с карточки, то анимация грубая будет

2024-02-13 03:25 UTC, Andrenord282 commented on frontend/src/scss/ui/_animal-card.scss
> +        & .animal-card__preview-img {
спасибо за совет! чет я такое не находил, поэтому сделал проще в первый раз
я сейчас переделал с this но не так как у тебя на скрине, я хотел сделать поведение, что бы независимо от того где на карточке курсор, картинка увеличивалась (то есть можно навести на имя или на параметры, анимация фотки отработает)

2024-02-13 10:46 UTC, Andrenord282 commented on frontend/src/scss/pages/index/sections/_animals.scss
> +        }
в section_header правки внес, в footer, animals_section, about_section обновил компонент)

2024-02-17 03:15 UTC, Christik approved these changes
Ура, давай мержить!) Только спуль себе, пожалуйста, сначала обновления из главной ветки, если они есть

2024-02-17 04:50 UTC, merged