feat: added scroll navigate on page/#61
qase-tms/shelterpaws pull request #71
Opened 2024-02-19 12:32 UTC by Andrenord282

2024-02-27 07:21 UTC, Christik requested changes
У меня менюшка работает хорошо, спасибо!)

2024-02-27 07:21 UTC, Christik commented on frontend/src/scss/ui/_animal-card.scss
> +        margin: 0 0.5em;
[!] Здесь, наверное, имел ввиду `margin: 0 0 .5em`. А то лишние боковые отступы появились)

2024-02-27 07:21 UTC, Christik commented on frontend/src/templates/general/header.njk
> +      link: "#"
[+] Давай пока заменим Main на About. И будем вести к соответственной секции. А то Main никуда не ведет

2024-02-27 07:21 UTC, Christik commented on frontend/src/templates/general/header.njk
> +      link: "#donations"
[+] Скорее всего, по клику на Donations в будущем будет открываться модалка. Давай пока закомментим этот пункт. И можно в коде оставить комментарий по поводу модалки.

2024-02-27 07:21 UTC, Christik commented on frontend/src/scss/ui/_param-list.scss
> +    text-align: center;
[!] Здесь `text-align: center` не нужен, наверное.

Чтобы пофиксить верстку, достаточно к `.param-list` добавить `flex-wrap: wrap`, чтобы элемента списка, которые не умещаются на одной строке, переносились на новую строку. И для красоты можно обновить гап, чтобы вертикальные отступы были меньше горизонтальных: `gap: 5px 10px;`

2024-03-04 05:38 UTC, Andrenord282 commented on frontend/src/templates/general/header.njk
> +      link: "#donations"
![image](https://github.com/qase-tms/shelterpaws/assets/79256226/75a0db1e-059f-489d-8da3-5e4b11047990)
я как понимаю именно кнопочка "Donate" будет отрабатывать модалку, а Donations это наверное список задонативших или что то в этом роде? поставлю заглушку с комментом

2024-03-04 05:40 UTC, Andrenord282 commented on frontend/src/scss/ui/_param-list.scss
> +    text-align: center;
спасибо, а я возился думая, что принципиально все впихнуть в одну строку)))

2024-03-09 05:41 UTC, merged